### PR TITLE
Forgotten Circles

### PR DESCRIPTION
**Pull request by relm923**
Add Forgotten Circles scenarios

Screen Shot 2020-07-04 at 12 11 37 PM

### CODE REVIEW

**Comment by relm923** [comment]
Fixes #28

**Comment by relm923** [comment]
@dmungin are you still maintaining this?

**Comment by dmungin** [comment]
Yes, sorry. I have not had much time recently. I am going to update dependencies and then we can get this PR merged.

**Comment by dmungin** [comment]
If you make any contributions going forward, you don't have to make updates to files in the `docs/` folder. Those files are generated by running the `npm run build` script.

**Comment by relm923** [comment]
@dmungin thanks!

**Pull request merged**
